### ISSUE TITLE
i have no idea how any of this works

### ISSUE THREAD

**Issue by FireBlaZe05** [Ajarmar/universal-pokemon-randomizer-zx#124]
am on mac receive this message when trying to open launcher
have java installed. dont know what to do

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/dabomstew/pkrandom/newgui/NewRandomizerGUI : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

**Comment by tom-overton** [comment]
Our suspicion is that you *do* have Java installed, but it is not a recent enough version to run the randomizer. Can you try the following for me?
1. Open Spotlight by either clicking the magnifying glass in the menu bar or by hitting Command + Space
2. Type "Terminal.app" in Spotlight and then press Enter to run the Terminal
3. In the Terminal, type `java -version`

If the reported version is below 1.8, you need to update your Java to run the randomizer.

**Comment by tom-overton** [comment]
@FireBlaZe05 did you get this working?

**Comment by tom-overton** [comment]
Since the OP hasn't been responsive, I'm closing this. If you need help, please reopen this again.
