### ISSUE TITLE
Limiting Pokemon

### ISSUE THREAD

**Issue by theernestrain** [Ajarmar/universal-pokemon-randomizer-zx#21]
For some reason whenever I click the "Limit Pokemon" and set it to gen 1 and 2, I get this error message. Randomizing Pokemon SoulSilver.

Randomizer Version: 4.0.1
Seed: 89171944398187
Settings String: 4.0.1AAgkAQSXAJoAnQAEAAEeRAABFAAAFABABAABAAAANKMAAAAAMgQyAQAICTIGBRZQb2tlbW9uIFNvdWxTaWx2ZXIgKFUpBLzRYePDOIo=
ROM: Pokemon SoulSilver (U)
Code: IPGE
Reported Support Level: Complete

java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.dabomstew.pkrandom.romhandlers.Gen4RomHandler.writeShedinjaEvolution(Gen4RomHandler.java:2347)
	at com.dabomstew.pkrandom.romhandlers.Gen4RomHandler.writeEvolutions(Gen4RomHandler.java:2320)
	at com.dabomstew.pkrandom.romhandlers.Gen4RomHandler.savePokemonStats(Gen4RomHandler.java:530)
	at com.dabomstew.pkrandom.romhandlers.Gen4RomHandler.savingROM(Gen4RomHandler.java:444)
	at com.dabomstew.pkrandom.romhandlers.AbstractDSRomHandler.saveRomFile(AbstractDSRomHandler.java:85)
	at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:613)
	at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$performRandomization$99(NewRandomizerGUI.java:830)
	at java.lang.Thread.run(Unknown Source)

**Comment by tom-overton** [comment]
Fix will be in the next release of the randomizer, thanks for the report! For now, you can either use 3.1.0 (because the bug was introduced in 4.0.0) or include Gen 3 when using "Limit Pokemon"

**Comment by theernestrain** [comment]
Thanks for responding. Great work btw! Looking forward to updates.
