### ISSUE TITLE
[Help] Exception occured at development setup.

### ISSUE THREAD

**Issue by HasBert** [Ajarmar/universal-pokemon-randomizer-zx#214]
Hey,
I want to setup the development like mentioned [here](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Building-Universal-Pokemon-Randomizer-ZX), but I can't figure out why this exception occurs when starting the program. I followed the steps 1 - 5 of [this document](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Building-Universal-Pokemon-Randomizer-ZX) .

```
/home/hasbert/.jdks/azul-1.8.0_292/bin/java -javaagent:/home/hasbert/Runnables/idea-IC-192.7142.36/lib/idea_rt.jar=36951:/home/hasbert/Runnables/idea-IC-192.7142.36/bin -Dfile.encoding=UTF-8 -classpath /home/hasbert/.jdks/azul-1.8.0_292/jre/lib/charsets.jar:/home/hasbert/.jdks/azul-1.8.0_292/jre/lib/crs-agent.jar:/home/hasbert/.jdks/azul-1.8.0_292/jre/lib/ext/cldrdata.jar:/home/hasbert/.jdks/azul-1.8.0_292/jre/lib/ext/dnsns.jar:/home/hasbert/.jdks/azul-1.8.0_292/jre/lib/ext/jaccess.jar:/home/hasbert/.jdks/azul-1.8.0_292/jre/lib/ext/legacy8ujsse.jar:/home/hasbert/.jdks/azul-1.8.0_292/jre/lib/ext/localedata.jar:/home/hasbert/.jdks/azul-1.8.0_292/jre/lib/ext/nashorn.jar:/home/hasbert/.jdks/azul-1.8.0_292/jre/lib/ext/openjsse.jar:/home/hasbert/.jdks/azul-1.8.0_292/jre/lib/ext/sunec.jar:/home/hasbert/.jdks/azul-1.8.0_292/jre/lib/ext/sunjce_provider.jar:/home/hasbert/.jdks/azul-1.8.0_292/jre/lib/ext/sunpkcs11.jar:/home/hasbert/.jdks/azul-1.8.0_292/jre/lib/ext/zipfs.jar:/home/hasbert/.jdks/azul-1.8.0_292/jre/lib/jce.jar:/home/hasbert/.jdks/azul-1.8.0_292/jre/lib/jfr.jar:/home/hasbert/.jdks/azul-1.8.0_292/jre/lib/jsse.jar:/home/hasbert/.jdks/azul-1.8.0_292/jre/lib/management-agent.jar:/home/hasbert/.jdks/azul-1.8.0_292/jre/lib/resources.jar:/home/hasbert/.jdks/azul-1.8.0_292/jre/lib/rt.jar:/home/hasbert/Code/universal-pokemon-randomizer-zx/out/production/universal-pokemon-randomizer-zx com.dabomstew.pkrandom.newgui.NewRandomizerGUI please-use-the-launcher
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.initExplicit(NewRandomizerGUI.java:585)
	at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.<init>(NewRandomizerGUI.java:337)
	at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$main$111(NewRandomizerGUI.java:3598)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**My launcher config**

![Screenshot from 2021-06-10 20-57-44](https://user-images.githubusercontent.com/19623805/121584463-c4dda380-ca31-11eb-918c-8855d44ccbfd.png)

**My project structure**

![Screenshot from 2021-06-10 20-58-21](https://user-images.githubusercontent.com/19623805/121584499-cdce7500-ca31-11eb-9341-c1f406d5b6b7.png)

![Screenshot from 2021-06-10 21-00-35](https://user-images.githubusercontent.com/19623805/121584524-d45cec80-ca31-11eb-989b-752031cc28c6.png)

**System (please fill in the following information):**

 - Operating System: 

   ```bash
   $ cat /etc/*release
   DISTRIB_ID=Pop
   DISTRIB_RELEASE=20.04
   DISTRIB_CODENAME=focal
   DISTRIB_DESCRIPTION="Pop!_OS 20.04 LTS"
   NAME="Pop!_OS"
   VERSION="20.04 LTS"
   ID=pop
   ID_LIKE="ubuntu debian"
   PRETTY_NAME="Pop!_OS 20.04 LTS"
   VERSION_ID="20.04"
   HOME_URL="https://pop.system76.com"
   SUPPORT_URL="https://support.system76.com"
   BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
   PRIVACY_POLICY_URL="https://system76.com/privacy"
   VERSION_CODENAME=focal
   UBUNTU_CODENAME=focal
   LOGO=distributor-logo-pop-os
   ```

 - Randomizer Version:  latest, (pulled with `git clone git@github.com:Ajarmar/universal-pokemon-randomizer-zx.git`)

 - IntelliJ Version:

   ```
   IntelliJ IDEA 2021.1.1 (Community Edition)
   Build #IC-211.7142.45, built on April 30, 2021
   Runtime version: 11.0.10+9-b1341.41 amd64
   VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
   Linux 5.11.0-7614-generic
   GC: ParNew, ConcurrentMarkSweep
   Memory: 1937M
   Cores: 16
   Registry: compiler.automake.allow.when.app.running=true
   Non-Bundled Plugins: google-java-format (1.9.0.1),  Docker (211.7142.13), org.jetbrains.kotlin (211-1.5.10-release-891-IJ7142.45)
   Kotlin: 211-1.5.10-release-891-IJ7142.45
   Current Desktop: pop:GNOME
   ```

I also used the debugger and made a breakpoint at  `com.dabomstew.pkrandom.newgui.NewRandomizerGUI.initExplicit(NewRandomizerGUI.java:585)`. It seems like the Java Swing components are not initialized. 

Could it be, that the JDK I'm using (`azul-1.8.0_292`) does not include the graphic components like Swing?

**Comment by tom-overton** [comment]
Hmm, I was running IntelliJ IDEA 2020.1.1 and a different JDK, so I downloaded 2021.1.1 and installed the same Azul JDK you're using and the randomizer still built and ran fine for me. Can you try using a different JDK? I think if a different JDK gives the same error, then we can conclusively rule out that it's a JDK issue.

**Comment by HasBert** [comment]
Thank you for your answer. I retested it with another machine (wiped recently, but same OS) and the same SDK and it worked. So I think the problem is my installation of IntelliJ or a problem with my OS. 

I will close this issue. Thank you for your time.
