### ISSUE TITLE
[Bug] Trying to open a Pokemon Y rom caused error

### ISSUE THREAD

**Issue by Mattoz7** [Ajarmar/universal-pokemon-randomizer-zx#216]
When I clicked which Rom to open, I clicked Pokemon Y which caused me to get the error report below.

ERROR REPORT:

Randomizer Version: 4.1.0
Java Version: 1.8.0_291, Java HotSpot(TM) 64-Bit Server VM
ROM: Pokemon Y
Code: CTR-P-EK2A
Reported Support Level: Complete

com.dabomstew.pkrandom.exceptions.RandomizerIOException: java.io.EOFException
	at com.dabomstew.pkrandom.romhandlers.Gen6RomHandler.loadedROM(Gen6RomHandler.java:262)
	at com.dabomstew.pkrandom.romhandlers.Abstract3DSRomHandler.loadRom(Abstract3DSRomHandler.java:74)
	at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$loadROM$97(NewRandomizerGUI.java:691)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.EOFException
	at java.io.RandomAccessFile.readFully(Unknown Source)
	at java.io.RandomAccessFile.readFully(Unknown Source)
	at com.dabomstew.pkrandom.ctr.RomfsFile.getContents(RomfsFile.java:56)
	at com.dabomstew.pkrandom.ctr.NCCH.getFile(NCCH.java:712)
	at com.dabomstew.pkrandom.romhandlers.Abstract3DSRomHandler.readFile(Abstract3DSRomHandler.java:190)
	at com.dabomstew.pkrandom.romhandlers.Abstract3DSRomHandler.readGARC(Abstract3DSRomHandler.java:175)
	at com.dabomstew.pkrandom.romhandlers.Gen6RomHandler.loadedROM(Gen6RomHandler.java:260)
	... 3 more

--ROM Diagnostics--
.code: D0F07ED8
romfs header: 82137600

ERROR REPORT END:

I have no idea what any of this means! But in the event I've made a mistake or something was wrong with either my rom or the randomizer, I hoped to post it here and have it checked as a just in case! Please let me know what went wrong and if there is anything on my end that I did wrong, let me know what it is and how to fix it in a clear manner. I'll do what I can but I don't really know what any of this stuff means, I just hope to get a randomized version of Pokemon Y for Citra emulator. 

Thank you.

**System (please complete the following information):**
 - Operating System: Windows 10
 - Java Version: java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)
 - Randomizer Version: 4.1.0

**Comment by tom-overton** [comment]
Just from the error message, I suspect something is wrong with the ROM. But just to double-check, can you upload the entire error log that the randomizer generates? You can just drag-and-drop it in the response text field to upload it.

**Comment by Mattoz7** [comment]
This is the full error log.

Thank you.
________________________________

**Comment by tom-overton** [comment]
Can you upload the file via github? I'm assuming you attached it to an email, but that doesn't actually send it to me.

**Comment by tom-overton** [comment]
Closing as it's been nearly a month with no response from OP. @Mattoz7 if you come back, please upload the file on *Github*; if you respond to this post via email none of the attachments actually come through.
