### ISSUE TITLE
OutOfMemory with 3ds roms

### ISSUE THREAD

**Issue by DaniloT** [Ajarmar/universal-pokemon-randomizer-zx#22]
I tried to randomize ultra moon, but after a long time waiting I saw the launcher-log.txt file and it had this error:

`java.lang.OutOfMemoryError
Exception in thread "Thread-2" java.lang.OutOfMemoryError
	at java.base/java.io.RandomAccessFile.readBytes(Native Method)
	at java.base/java.io.RandomAccessFile.read(RandomAccessFile.java:408)
	at java.base/java.io.RandomAccessFile.readFully(RandomAccessFile.java:472)
	at java.base/java.io.RandomAccessFile.readFully(RandomAccessFile.java:448)
	at com.dabomstew.pkrandom.ctr.NCCH.rebuildRomfs(NCCH.java:453)
	at com.dabomstew.pkrandom.ctr.NCCH.saveAsNCCH(NCCH.java:295)
	at com.dabomstew.pkrandom.romhandlers.Abstract3DSRomHandler.saveRomFile(Abstract3DSRomHandler.java:95)
	at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:613)
	at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$performRandomization$99(NewRandomizerGUI.java:829)
	at java.base/java.lang.Thread.run(Thread.java:835)
`

I ran it from the launcher.jar, my HD has over 40gb free, I have 16gb of ram with 4-5gb free while running the randomizer, I don't get why I'm getting this, any help?

**Comment by tom-overton** [comment]
Can you run `java -version` in a command line prompt and report back what it says? We've seen people run out of memory before, but usually this because they ran the randomizer *without* using launcher.jar, so their Java heap size is too small.

**Comment by DaniloT** [comment]
```
java version "12.0.2" 2019-07-16
Java(TM) SE Runtime Environment (build 12.0.2+10)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)
```

I managed to run the randomizer, I changed my paging file size, it was 16-4000MB and I kicked it up a bunch (16-20000) to test it and after a reboot, the randomizer worked, thanks for trying to help though!

**Comment by deathdude87** [comment]
i have the most recent java but when i double click the windows launcher it bring up the command prompt saying the heap size is exceeded -Xmx4096M and it couldnt create the java virtual machine

**Comment by tom-overton** [comment]
@deathdude87 This indicates that you have 32-bit Java installed. Please install 64-bit Java as per [the Java wiki page](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java)

Also, please don't respond on closed issues like this, since it makes it hard for you to get help. If you have further launcher issues after installing 64-bit Java, head over to #221
