### ISSUE TITLE
[Bug] Ultra Moon version not identified

### ISSUE THREAD

**Issue by formlesstree4** [Ajarmar/universal-pokemon-randomizer-zx#266]
**Describe the bug**
When loading Ultra Moon, the ROM information section does not display the version information of the ROM, regardless if it is a 3ds file or cia file. Additionally, this means that when applying an update cia file, there is a crash dump on the screen

**To Reproduce**
1. Load the application
2. Press "Open ROM"
3. Select Pokemon Ultra Moon

**Expected behavior**
The version should appear (as according to [this](https://imgur.com/sHWims4) image in the Wiki) and applying an update file should work as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/6273530/128806941-843bbb93-83f5-4a28-ac63-83307164203e.png)

![image](https://user-images.githubusercontent.com/6273530/128806968-4872a94e-933c-4a8b-9b09-986b3dbef61e.png)

![image](https://user-images.githubusercontent.com/6273530/128807009-dbf6a4ad-6754-4393-9c11-b9ce83d3eed8.png)

**System (please complete the following information):**
 - Operating System: Windows 10 Professional 21H1 (19043.1110)
 - Java Version: java version "16.0.1" 2021-04-20 (according to java -version)
 - Randomizer Version: v4.2.1

**Additional context**
Here is a copy of the stack trace that gets printed to the Console when attempting to "Load Game Update" to the copy of Pokemon Ultra Moon
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "actualUpdateTitleId" is null
        at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.applyGameUpdateMenuItemActionPerformed(NewRandomizerGUI.java:1107)
        at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$new$70(NewRandomizerGUI.java:480)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
        at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1022)
        at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1066)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6382)
        at java.desktop/java.awt.Container.processEvent(Container.java:2264)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by tom-overton** [comment]
This error is *probably* because the update files are invalid. Did you dump the CIA files via GodMode9?
