### ISSUE TITLE
[Help] when i try to randomize a 3ds rom when i click randomize (save) and i output it as xci then it says failed to add rom to disk

### ISSUE THREAD

**Issue by miraculousagr** [Ajarmar/universal-pokemon-randomizer-zx#272]
here is the error messeage

Randomizer Version: 4.2.1
Seed: 200506818528646
Settings String: 316AiIEAgKJAowCjwIBAAIeJAAECQAAFABAAQACAgAAAAAAAAAAMgEyAVoICTIICAAyAwlQb2tlbW9uIFk4R6Xr48M4ig==
Java Version: 16.0.1, Java HotSpot(TM) 64-Bit Server VM
ROM: Pokemon Y
Code: CTR-P-EK2A
Reported Support Level: Complete

java.lang.ArrayIndexOutOfBoundsException: Index 115 out of bounds for length 115
	at com.dabomstew.pkrandom.romhandlers.Gen6RomHandler.updatePokedexAreaDataXY(Gen6RomHandler.java:1577)
	at com.dabomstew.pkrandom.romhandlers.Gen6RomHandler.setEncountersXY(Gen6RomHandler.java:1432)
	at com.dabomstew.pkrandom.romhandlers.Gen6RomHandler.setEncounters(Gen6RomHandler.java:1328)
	at com.dabomstew.pkrandom.romhandlers.AbstractRomHandler.randomEncounters(AbstractRomHandler.java:902)
	at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:446)
	at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$performRandomization$105(NewRandomizerGUI.java:880)
	at java.base/java.lang.Thread.run(Thread.java:831)

--ROM Diagnostics--
.code: D0F07ED8
romfs header: BBE65BE0
DllField.cro: 9575E9CD
DllPoke3Select.cro: 2A592492
a/0/1/2: 23085783
a/0/3/8: C4673417
a/0/4/0: 27BFA7A4
a/0/7/4: D82C84F1
a/0/9/3: F739084C
a/2/1/2: 974DAD20
a/2/1/4: 165E653E
a/2/1/5: B6F5DFA9
a/2/1/6: FE88377C
a/2/1/8: 7834E6AE
**

**Comment by miraculousagr** [comment]
[error_2021-08-23-19-18-21.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/7033447/error_2021-08-23-19-18-21.txt)

**Comment by tom-overton** [comment]
The same seed/settings combination works fine for me: 
[test.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/7039919/test.log)

Looking at your ROM Diagnostics, I see some notable differences:
Yours:
```
romfs header: BBE65BE0
a/0/1/2: 23085783
a/0/3/8: C4673417
a/0/4/0: 27BFA7A4
```

Mine:
```
romfs header: 82137600
a/0/1/2: C4BF77F6
a/0/3/8: 7C3D4F79
a/0/4/0: 9CC8CE76
```

Is this some sort of ROM hack?
