### ISSUE TITLE
Static Pokemon > Random (Similar Strength) seems to not work on HeartGold

### ISSUE THREAD

**Issue by b-ggs** [Ajarmar/universal-pokemon-randomizer-zx#3]
It throws the exception:

```
Randomizer Version: 1721
ROM: Pokemon HeartGold (U)
Code: IPKE
Reported Support Level: Complete

java.lang.NullPointerException
	at com.dabomstew.pkrandom.romhandlers.AbstractRomHandler.getBelowAveragePlacements(AbstractRomHandler.java:3950)
	at com.dabomstew.pkrandom.romhandlers.AbstractRomHandler.pickReplacement(AbstractRomHandler.java:3751)
	at com.dabomstew.pkrandom.romhandlers.AbstractRomHandler.randomizeStaticPokemon(AbstractRomHandler.java:2043)
	at com.dabomstew.pkrandom.Randomizer.maybeChangeAndLogStaticPokemon(Randomizer.java:814)
	at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:370)
	at com.dabomstew.pkrandom.gui.RandomizerGUI$3.run(RandomizerGUI.java:2188)

```

With the following settings: [xpa-hpg-random-settings.zip](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/4731594/xpa-hpg-random-settings.zip)

The randomizer worked with those settings after I had changed `Static Pokemon` to `Completely Random` instead.

Thank you!

**Comment by Ajarmar** [comment]
Thanks for pointing this out. It seems to be an issue with every game, not just HG/SS, occurring when you try to use Random (similar strength) for Static Pokemon while not randomizing Trainer Pokemon.

Fixed in commit 79a4f1b - will be included in the next release.
