### ISSUE TITLE
Unhandled Exception when trying to load ROM into randomizer

### ISSUE THREAD

**Issue by WixDraco151** [Ajarmar/universal-pokemon-randomizer-zx#361]
I receive an Unhandled Exception error when trying to load a decrypted .3DS ROM file. I have no problems with opening the randomizer itself. I'm running 64-bit OS on Windows 11, Java 8 update 311, w/ the 4.2.1 randomizer version. I've listed the error report below:

Randomizer Version: 4.2.1
Java Version: 1.8.0_311, Java HotSpot(TM) 64-Bit Server VM
ROM: Pokemon Ultra Moon
Code: CTR-P-A2BA
Reported Support Level: Complete

com.dabomstew.pkrandom.exceptions.RandomizerIOException: java.io.EOFException
	at com.dabomstew.pkrandom.romhandlers.Gen7RomHandler.getStarters(Gen7RomHandler.java:993)
	at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.populateDropdowns(NewRandomizerGUI.java:3387)
	at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.romLoaded(NewRandomizerGUI.java:2525)
	at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$null$99(NewRandomizerGUI.java:718)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.awt.Dialog.show(Unknown Source)
	at java.awt.Component.show(Unknown Source)
	at java.awt.Component.setVisible(Unknown Source)
	at java.awt.Window.setVisible(Unknown Source)
	at java.awt.Dialog.setVisible(Unknown Source)
	at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$null$98(NewRandomizerGUI.java:700)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.io.EOFException
	at java.io.RandomAccessFile.readFully(Unknown Source)
	at java.io.RandomAccessFile.readFully(Unknown Source)
	at com.dabomstew.pkrandom.ctr.RomfsFile.getContents(RomfsFile.java:56)
	at com.dabomstew.pkrandom.ctr.NCCH.getFile(NCCH.java:712)
	at com.dabomstew.pkrandom.romhandlers.Abstract3DSRomHandler.readFile(Abstract3DSRomHandler.java:190)
	at com.dabomstew.pkrandom.romhandlers.Abstract3DSRomHandler.readGARC(Abstract3DSRomHandler.java:175)
	at com.dabomstew.pkrandom.romhandlers.Gen7RomHandler.getStarters(Gen7RomHandler.java:972)
	... 39 more

--ROM Diagnostics--
.code: 1C3F1290
romfs header: FAB54485
a/0/1/1: E8CC46AA
a/0/1/4: 14B009D5
a/0/1/5: AA8FA0AF
a/0/1/7: 7D4D7A45
a/0/3/2: 0FB62104
a/0/4/2: 2D66B8A4
a/0/7/7: 37A8FE41
a/0/8/3: 0FB10C58
a/0/9/1: 5869B140

**Comment by tom-overton** [comment]
Could you try again with the newly-released v4.3.0? https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases/tag/v4.3.0
