### ISSUE TITLE
[Bug] Launcher doesn't like certain characters in directory names

### ISSUE THREAD

**Issue by truec** [Ajarmar/universal-pokemon-randomizer-zx#400]
I got a variety of failed attempts while trying to launch the randomizer.  I was too stupid to actually look at the command prompt or I would have realized sooner that the issue was the launcher (or maybe this is an inherent problem with Java?) was pitching a fit about the name of the directory it was in, specifically that it ended in a '+'.  Several times the Randomizer failed to launch outright; other times it launched but immediately informed me it didn't have write access.  After changing the directory name, all issues are resolved, but I thought I should put this out.

I included the errors from the last attempt that ended in failure to launch before I realized the directory name was the issue.

To Reproduce, put Randomizer files in a folder ending in '+' and attempt to launch.

Error text:
Exception in thread "AWT-EventQueue-0" java.nio.file.InvalidPathException: Trailing char < > at index 43: E:\games\emulation\Randomizers\Pokemon\UPR6
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:191)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at java.desktop/sun.awt.shell.ShellFolder.getShellFolder(ShellFolder.java:247)
        at java.desktop/sun.swing.FilePane$DetailsTableModel.updateColumnInfo(FilePane.java:715)
        at java.desktop/sun.swing.FilePane.doDirectoryChanged(FilePane.java:1646)
        at java.desktop/sun.swing.FilePane.propertyChange(FilePane.java:1703)
        at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
        at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
        at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
        at java.desktop/java.awt.Component.firePropertyChange(Component.java:8732)
        at java.desktop/javax.swing.JFileChooser.setCurrentDirectory(JFileChooser.java:595)
        at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.initFileChooserDirectories(NewRandomizerGUI.java:608)
        at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.<init>(NewRandomizerGUI.java:349)
        at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$main$118(NewRandomizerGUI.java:3783)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Press any key to exit...

**System (please complete the following information):**
 - Operating System: Windows 10
 - Java Version: 8
 - Randomizer Version: 4.3.0

**Additional context**
One time I swear it launched 1.7.2, but I was never able to reproduce that and may have hallucinated it.

**Comment by tom-overton** [comment]
Thanks for reporting this! It will be fixed in the next release.
