### ISSUE TITLE
4.3.0, 4.2.1, and 4.2.0 error code issue. please help.

### ISSUE THREAD

**Issue by DarkRna** [Ajarmar/universal-pokemon-randomizer-zx#405]
i have tried running my games with a cxi file and it gives me this error code: error_2022-03-20-17-08-22. I used all the 3ds games i had to see if it worked differently which it didn't which i used ultra moon, omega ruby, sun, and x. I also did try to do a layered file but i couldn't get   it to work. it did give me the seed but it wouldn't randomize it. I did even check that i had the right version of java and the first time around i didn't but i do now but it still isn't working. i mean i do have the 64 bit. i just wonder if i am still doing something wrong.  i just don't know what to do cus i have been trying to fix this issue for a month.

**Comment by tom-overton** [comment]
Can you please post the contents of the error log that's generated? That's not an error code; that's a text file that will explain what the actual error is.

**Comment by DarkRna** [comment]
Randomizer Version: 4.3.0
Seed: 24933551383711
Settings String: 317QAgEAQTRAtQC1wIEAAEeRAABFAAAFABABAABAAAAAAAAAAAAMgQyAQAICTIICAAyAAISUG9rZW1vbiBVbHRyYSBNb29uAZAON+PDOIo=
Java Version: 1.8.0_321, Java HotSpot(TM) 64-Bit Server VM
ROM: Pokemon Ultra Moon
Code: CTR-P-A2BA
Reported Support Level: Complete

com.dabomstew.pkrandom.exceptions.RandomizerIOException: java.io.FileNotFoundException: C:\Users\poo.cxi (Access is denied)
	at com.dabomstew.pkrandom.romhandlers.Abstract3DSRomHandler.saveRomFile(Abstract3DSRomHandler.java:93)
	at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:670)
	at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$performRandomization$112(NewRandomizerGUI.java:918)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: C:\Users\poo.cxi (Access is denied)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(Unknown Source)
	at java.io.RandomAccessFile.<init>(Unknown Source)
	at java.io.RandomAccessFile.<init>(Unknown Source)
	at com.dabomstew.pkrandom.ctr.NCCH.saveAsNCCH(NCCH.java:253)
	at com.dabomstew.pkrandom.romhandlers.Abstract3DSRomHandler.saveRomFile(Abstract3DSRomHandler.java:91)
	... 3 more

--ROM Diagnostics--
File name: Pokemon Ultra Moon (USA) (En,Ja,Fr,De,Es,It,Zh,Ko) Decrypted.3ds
.code: 1C3F1290
romfs header: FAB54485
Battle.cro: 1025191A
Shop.cro: 24E3E8B9
a/0/1/1: E8CC46AA
a/0/1/3: 428BEF17
a/0/1/4: 14B009D5
a/0/1/5: AA8FA0AF
a/0/1/7: 7D4D7A45
a/0/1/8: A26BE810
a/0/1/9: 4EF71745
a/0/3/0: BB54E5FD
a/0/3/1: 88B0CBA9
a/0/3/2: 0FB62104
a/0/3/3: A1B4CBA9
a/0/3/4: A0816130
a/0/3/5: 739E8D75
a/0/3/6: FF633A6D
a/0/3/7: 09CE93FB
a/0/3/8: 0A51E183
a/0/3/9: 09D78158
a/0/4/2: 2D66B8A4
a/0/6/2: 82273273
a/0/7/7: 37A8FE41
a/0/8/3: 0FB10C58
a/0/9/1: 5869B140
a/0/9/2: E34345E0
a/1/0/6: 95274370
a/1/0/7: D0C7992F
a/1/5/9: 82A75234
a/2/7/1: CC060249
 
is this what you were meaning?

**Comment by tom-overton** [comment]
Yep, that's exactly what I was missing. It looks like the randomizer is trying to write a CXI file in a place where it doesn't have permissions to write anything. Can you try writing your CXI file to a different location?
