### ISSUE TITLE
[Bug] an unhandled exceptioon

### ISSUE THREAD

**Issue by LazyAssOverlord** [Ajarmar/universal-pokemon-randomizer-zx#452]
i am getting an error every time i try to randomize my Omega Ruby rom and i am unsure on what the issue is. Any help would be appreciated.

Randomizer Version: 4.4.0
Seed: 15975594075321
Settings String: 318ABgEAUL7AP4AAQEEAAIeBllCTACyTAABCQABAgAAAAAAAgAAMkkywQAICTIHBwAyAAISUG9rZW1vbiBPbWVnYSBSdWJ5I83iGOPDOIo=
Java Version: 1.8.0_333, Java HotSpot(TM) 64-Bit Server VM
ROM: Pokemon Omega Ruby
Code: CTR-P-ECRA
Reported Support Level: Complete

com.dabomstew.pkrandom.exceptions.RandomizerIOException: java.io.FileNotFoundException: C:\Program Files\3DS Games.cxi (Access is denied)
	at com.dabomstew.pkrandom.romhandlers.Abstract3DSRomHandler.saveRomFile(Abstract3DSRomHandler.java:91)
	at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:670)
	at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$performRandomization$113(NewRandomizerGUI.java:919)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: C:\Program Files\3DS Games.cxi (Access is denied)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(Unknown Source)
	at java.io.RandomAccessFile.<init>(Unknown Source)
	at java.io.RandomAccessFile.<init>(Unknown Source)
	at com.dabomstew.pkrandom.ctr.NCCH.saveAsNCCH(NCCH.java:253)
	at com.dabomstew.pkrandom.romhandlers.Abstract3DSRomHandler.saveRomFile(Abstract3DSRomHandler.java:89)
	... 3 more

--ROM Diagnostics--
File name: 3DS1124 - Pokemon Omega Ruby (USA)(En,Fr,Ge,It,Ja,Ko,Es)-decrypted.3ds
.code: 575A1629
romfs header: D39632B9
DllBattle.cro: E78107DF
DllField.cro: F929EB93
DllPoke3Select.cro: F4A1F22E
DllShinkaDemo.cro: 53AC2B89
a/0/1/3: BD3DF991
a/0/2/9: 3F312B82
a/0/3/6: F2F2FCFE
a/0/3/8: 9C55C332
a/0/7/1: 3012FCBF
a/0/7/2: 75638696
a/0/7/3: 0EF80A2A
a/0/7/4: 63BC908F
a/0/7/5: 79E211CF
a/0/7/6: 631C8EAA
a/0/7/7: 3467A16A
a/0/7/8: 29518B34
a/0/7/9: FCC62512
a/0/8/0: B5DD59B9
a/0/8/1: 23B7F22E
a/0/8/2: BE187B12
a/0/8/3: F9B2A3A0
a/0/8/4: 5C6D7C5B
a/0/8/5: 4F20E0AD
a/0/8/6: AFF7DD4F
a/0/9/1: 2AA511AA
a/1/8/1: 0C1F0B7B
a/1/8/9: D17DC884
a/1/9/1: C03B6E88
a/1/9/2: 21DCE891
a/1/9/3: 43D2B7D0
a/1/9/5: ABB02044
a/1/9/6: 8219BA02
a/1/9/7: 06267B89

**Comment by tom-overton** [comment]
Try saving the CXI to somewhere else; you're trying to save it to C:\Program Files right now, and I'm almost certain the randomizer doesn't have access to that folder.
