### ISSUE TITLE
Gen II games can't use Gen 8 rulesets

### ISSUE THREAD

**Issue by JoseTavaresFilho** [Ajarmar/universal-pokemon-randomizer-zx#48]
It gets an error log on Silver as example but Gold and Crystal won't work too. 

Randomizer Version: 4.0.1
Seed: 121033182936774
Settings String: 4.0.1AigEAQQAAAMABgAEAAEeRAABFAAAFABABAABAAAAAAAAAAQAMgQyAQAICTIICBJQb2tlbW9uIFNpbHZlciAoVSllHCzV48M4ig==
ROM: Pokemon Silver (U)
Code: AAXE
Reported Support Level: Complete

java.lang.NullPointerException
	at com.dabomstew.pkrandom.romhandlers.AbstractRomHandler.updatePokemonStats(AbstractRomHandler.java:278)
	at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:150)
	at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$performRandomization$99(NewRandomizerGUI.java:830)
	at java.lang.Thread.run(Unknown Source)

**Comment by tom-overton** [comment]
Yep, this is a known bug. We fixed it in 97b02ea610c4df7961254d9d92c26c661d585321, so it will work in the next update. Thanks for the report!
