### ISSUE TITLE
at com.dabomstew.pkrandom.romhandlers.AbstractRomHandler.setIllegalEvos(AbstractRomHandler.java:1575)

### ISSUE THREAD

**Issue by FwgKnight** [Ajarmar/universal-pokemon-randomizer-zx#488]
"at com.dabomstew.pkrandom.romhandlers.AbstractRomHandler.setIllegalEvos(AbstractRomHandler.java:1575)" Appears in the cmd prompt hundreds of times when trying to Save to rom.

Settings string used: 319ADIEAhIBAIEBBwCRAAQeJAgEiAAAiAAuASegEgAAAAAAAAC4xkHGBFoNCTIIBATGRwECEEZpcmUgUmVkIChVKSAxLjHR0spo48M4ig==

First time even using one of these, so I may just be dumb. Trying on FireRed 1.1 (U) if that changes anything.

**Comment by tom-overton** [comment]
The problem here is that we allow you to select "Rival Carries Starter" at all when "Random Every Level" evolutions are selected; we did not intend for those two settings to be used simultaneously. In the next release, this will be fixed by preventing you from using these two settings at the same time. For now, just turn off "Rival Carries Starter" in your settings and everything should work.
