### ISSUE TITLE
Type Theming areas in Pokemon AS does not work.

### ISSUE THREAD

**Issue by The-Silver-Kid** [Ajarmar/universal-pokemon-randomizer-zx#60]
When attempting to randomize Pokemon Alpha Sapphire (with update 1.4) the following error is thrown

```C
Randomizer Version: 4.0.2
Seed: 196091591746646
Settings String: 313AQgE+kj7AP4AAQEyxgSoKBhiKgDQKtA9GBgBGgAAAAAAAAAAMrky+aYICTIHBxZQb2tlbW9uIEFscGhhIFNhcHBoaXJl+Mt9ruPDOIo=
Java Version: 1.8.0_271, Java HotSpot(TM) 64-Bit Server VM
ROM: Pokemon Alpha Sapphire
Code: CTR-P-ECLA
Reported Support Level: Complete

java.lang.NullPointerException
	at java.util.TreeMap.getEntry(Unknown Source)
	at java.util.TreeMap.containsKey(Unknown Source)
	at com.dabomstew.pkrandom.romhandlers.AbstractRomHandler.enhanceRandomEncountersORAS(AbstractRomHandler.java:1381)
	at com.dabomstew.pkrandom.romhandlers.AbstractRomHandler.randomEncounters(AbstractRomHandler.java:729)
	at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:433)
	at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$performRandomization$99(NewRandomizerGUI.java:847)
	at java.lang.Thread.run(Unknown Source)
```
Switching from type theme areas to any of the other 3 options works fine.

**Comment by tom-overton** [comment]
Thanks for the report. It will be fixed in the next release. For now, you should be able to use Area 1-to-1 Mapping or Global 1-to-1 Mapping if you want to use Type Themed Areas with ORAS.
