### ISSUE TITLE
[Bug] Unsupported Operation Exception - Unsure cause

### ISSUE THREAD

**Issue by Hogwobblin** [Ajarmar/universal-pokemon-randomizer-zx#645]
Randomizer Version: 4.6.0 + V0.9.2
Seed: 195047717626807
Settings String: 324Y4MBEgQBAAQABwAyqCCkRAABKgeoKqhABAABiwAAAAAAAQSYMgQyAQIICTIGCQAyEQIABhhQb2tlbW9uIEZpcmUgUmVkIChVKSAxLjARWqnz48M4ig==
Java Version: 20.0.1, Java HotSpot(TM) 64-Bit Server VM
ROM: Pokemon Fire Red (U) 1.0
Code: BPRE
Reported Support Level: Complete

java.lang.UnsupportedOperationException
	at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142)
	at java.base/java.util.ImmutableCollections$AbstractImmutableList.set(ImmutableCollections.java:260)
	at java.base/java.util.Collections.swap(Collections.java:501)
	at java.base/java.util.Collections.shuffle(Collections.java:462)
	at com.dabomstew.pkrandom.romhandlers.AbstractRomHandler.pickTrainerMovesets(AbstractRomHandler.java:2354)
	at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:480)
	at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$performRandomization$117(NewRandomizerGUI.java:1056)
	at java.base/java.lang.Thread.run(Thread.java:1623)

--ROM Diagnostics--
File name: Pokemon - FireRed Version (USA).gba
Original ROM CRC32: DD88761C

Not sure what the error here is telling me, could you ellaborate?

**Comment by tom-overton** [comment]
```
Randomizer Version: 4.6.0 + V0.9.2
```
Indicates this isn't our build of the randomizer. Where did you get it from? You'll have to consult with them to figure out the cause of your issue.

**Comment by Hogwobblin** [comment]
This is voliols recent fork with paletter randomization, they don't have an issue report section unfortunately. I used your current version and I cannot replicate so I guess it's currently a bad fork. Apologies for bothering you.

https://github.com/voliol/universal-pokemon-randomizer

**Comment by tom-overton** [comment]
Ahh, I see. No worries! Thanks for letting me know about this; I think this fork is the cause behind another one of the issues in our list, so I'm glad you pointed this out! And yeah, unfortunately we can't help if something is working in our version, but broken in a fork. I wish that this other branch had an issue report somewhere.
