### ISSUE TITLE
[Help] Error_2023-07-09-16-29-10

### ISSUE THREAD

**Issue by hiddenoni** [Ajarmar/universal-pokemon-randomizer-zx#648]
After I tried to randomize I always get and error code :

Randomizer Version: 4.1.0
Seed: 67985516117101
Settings String: 314AAgkAUKJAowCjwIEAAIeBgBCFAAAFAABBAABMgAH/78AAgAAMgQywQAICTIHBwAyCVBva2Vtb24gWG5SDiTjwziK
Java Version: 1.8.0_371, Java HotSpot(TM) 64-Bit Server VM
ROM: Pokemon X
Code: CTR-P-EKJA
Reported Support Level: Complete

com.dabomstew.pkrandom.exceptions.RandomizerIOException: Error when building romfs: File: a/1/0/1, offset: 12764, size: 17032608
	at com.dabomstew.pkrandom.ctr.NCCH.rebuildRomfs(NCCH.java:470)
	at com.dabomstew.pkrandom.ctr.NCCH.saveAsNCCH(NCCH.java:300)
	at com.dabomstew.pkrandom.romhandlers.Abstract3DSRomHandler.saveRomFile(Abstract3DSRomHandler.java:95)
	at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:659)
	at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$performRandomization$102(NewRandomizerGUI.java:869)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Es steht nicht genug Speicherplatz auf dem Datenträger zur Verfügung
	at java.io.RandomAccessFile.writeBytes(Native Method)
	at java.io.RandomAccessFile.write(Unknown Source)
	at com.dabomstew.pkrandom.ctr.NCCH.rebuildRomfs(NCCH.java:465)
	... 5 more

--ROM Diagnostics--
.code: 067988FE
romfs header: FD78093D
DllField.cro: 9ECEE09B
DllPoke3Select.cro: 2A592492
DllShinkaDemo.cro: 43C33CF5
a/0/1/2: F0617248
a/0/3/8: 7C3D4F79
a/0/4/0: 9CC8CE76
a/0/7/4: D82C84F1
a/0/9/3: F739084C
a/2/0/2: 76467D4C
a/2/1/2: 974DAD20
a/2/1/4: 165E653E
a/2/1/5: B6F5DFA9
a/2/1/6: FE88377C
a/2/1/8: 7834E6AE
a/2/1/9: 8219BA02

**Comment by tom-overton** [comment]
From your error log, it looks like your disk ran out of space:
```
Caused by: java.io.IOException: Es steht nicht genug Speicherplatz auf dem Datenträger zur Verfügung
```
Can you try clearing out some space or saving to another location? CXIs are pretty large, so make sure you have roughly 4 GB of space available. Alternatively, the layeredfs option is much more space-efficient.
