### ISSUE TITLE
[Help] im trying to ramdomize pokemon ultra moon but i get this error

### ISSUE THREAD

**Issue by tomasbd** [Ajarmar/universal-pokemon-randomizer-zx#663]
Randomizer Version: 4.6.0
Java Version: 16.0.2, Java HotSpot(TM) 64-Bit Server VM
ROM: Pokemon Ultra Moon
Code: CTR-P-A2BA
Reported Support Level: Complete

java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
	at com.dabomstew.pkrandom.romhandlers.Gen7RomHandler.populateEvolutions(Gen7RomHandler.java:582)
	at com.dabomstew.pkrandom.romhandlers.Gen7RomHandler.loadPokemonStats(Gen7RomHandler.java:413)
	at com.dabomstew.pkrandom.romhandlers.Gen7RomHandler.loadedROM(Gen7RomHandler.java:308)
	at com.dabomstew.pkrandom.romhandlers.Abstract3DSRomHandler.loadRom(Abstract3DSRomHandler.java:69)
	at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$loadROM$106(NewRandomizerGUI.java:778)
	at java.base/java.lang.Thread.run(Thread.java:831)

--ROM Diagnostics--
The ROM you loaded is not a clean, official ROM.
Randomizing ROM hacks or bad ROM dumps is not supported and may cause issues.

File name: Pokemon Penumbra Moon v1.0.5 Expended.3ds
.code: 2AF29FAF
romfs header: 4379F2CB
a/0/1/4: 772BFBDC
a/0/1/7: 70F9D7F1
a/0/3/2: BBCAABEA
a/0/4/2: 07D4D542
a/0/7/7: 37A8FE41
a/0/8/3: 2CC4D1D9
a/0/9/1: 5869B140

**Comment by tom-overton** [comment]
Sorry, we don't expect ROM hacks. I did some investigation and it looks like this ROM hack is changing evolutions, hence why it's crashing the randomizer.
