### ISSUE TITLE
[Help] Exception in thread "Thread-5"

### ISSUE THREAD

**Issue by Mantra1776** [Ajarmar/universal-pokemon-randomizer-zx#669]
When attempting to save/randomize Omega Ruby i get the following exception 

Exception in thread "Thread-5" java.lang.OutOfMemoryError: Java heap space
        at com.dabomstew.pkrandom.ctr.NCCH.rebuildRomfs(NCCH.java:480)
        at com.dabomstew.pkrandom.ctr.NCCH.saveAsNCCH(NCCH.java:316)
        at com.dabomstew.pkrandom.romhandlers.Abstract3DSRomHandler.saveRomFile(Abstract3DSRomHandler.java:90)
        at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:680)
        at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$performRandomization$111(NewRandomizerGUI.java:1023)
        at com.dabomstew.pkrandom.newgui.NewRandomizerGUI$$Lambda$155/1951424665.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

I understand running out of heap space, but how can i avoid/fix that?

**Comment by Mantra1776** [comment]
Update: I fixed it. for those who need to know simply press the iwndow key and search "view advanced system settings".
at the bottom is "Enviroment Variables". Click that. On system variables add a new variable. Name it _JAVA_OPTIONS and set the value to -Xmx?????M witht eh? being whatever number of megabytes. The number will be how much ram java is allowed to use. in my case it is -Xmx16384M as i have 128gb of ram and can afford to spare 16gb.
