### ISSUE TITLE
[Help] 

### ISSUE THREAD

**Issue by PunPun00** [Ajarmar/universal-pokemon-randomizer-zx#686]
When saving the game file for Pokemon X after randomizing everything I wanted to, this is what pops up in the cmd prompt section 

Exception in thread "Thread-5" java.lang.OutOfMemoryError: Java heap space at com.dabomstew.pkrandom.ctr.NCCH.rebuildRomfs(NCCH.java:480) at com.dabomstew.pkrandom.ctr.NCCH.saveAsNCCH(NCCH.java:316) at com.dabomstew.pkrandom.romhandlers.Abstract3DSRomHandler.saveRomFile(Abstract3DSRomHandler.java:90) at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:680) at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$performRandomization$111(NewRandomizerGUI.java:1023) at com.dabomstew.pkrandom.newgui.NewRandomizerGUI$$Lambda$154/325018577.run(Unknown Source) at java.lang.Thread.run(Unknown Source)

The resulting CXI file is always only 16684KB big so there is clearly something not working correctly 
Im on Windows 10
Using Version 4_6_0

**Comment by dweipert-3138720606** [comment]
Possibly related: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/22

Read through the issue and see if that fixes it for you.
