### ISSUE TITLE
[help]

### ISSUE THREAD

**Issue by Shade4X4** [Ajarmar/universal-pokemon-randomizer-zx#692]
I am trying to randomize Pokemon Omega Ruby and it is not working. I decided it would be good to check the logs, here is what I found Exception in thread "Thread-2" java.lang.OutOfMemoryError: Java heap space
        at com.dabomstew.pkrandom.ctr.NCCH.rebuildRomfs(NCCH.java:480)
        at com.dabomstew.pkrandom.ctr.NCCH.saveAsNCCH(NCCH.java:316)
        at com.dabomstew.pkrandom.romhandlers.Abstract3DSRomHandler.saveRomFile(Abstract3DSRomHandler.java:90)
        at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:680)
        at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$performRandomization$111(NewRandomizerGUI.java:1023)
        at com.dabomstew.pkrandom.newgui.NewRandomizerGUI$$Lambda$336/0x00000001003b5c40.run(Unknown Source)
        at java.base/java.lang.Thread.run(Thread.java:829). I am on v4.6.0.

**Comment by dweipert-3138720606** [comment]
Probably related: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/22

Read through the issue and see if that fixes it for you.

**Comment by Shade4X4** [comment]
> Probably related: #22
> 
> Read through the issue and see if that fixes it for you.

I also saw that post before and tried it. It didn't end up working. Any other tips?

**Comment by Shade4X4** [comment]
I fixed it buy following Issue #86. Mainly this https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java#when-i-try-to-randomize-the-game-it-fails-and-i-see-something-like-picked-up-_java_options--xmx512m-in-launcher-logtxt I have no idea why this fixed it. But it did.
