### ISSUE TITLE
[Help] Getting an unhandled exception error

### ISSUE THREAD

**Issue by TommoMidd** [Ajarmar/universal-pokemon-randomizer-zx#722]
**Describe your problem clearly:** 
I have a ROM i try and use it it loads then it just comes up with the error code. the text file says this
Randomizer Version: 4.6.0
Java Version: 1.8.0_401, Java HotSpot(TM) 64-Bit Server VM
ROM: Pokemon Ultra Sun
Code: CTR-P-A2AA
Reported Support Level: Complete

com.dabomstew.pkrandom.exceptions.RandomizerIOException: java.io.EOFException
	at com.dabomstew.pkrandom.romhandlers.Gen7RomHandler.loadedROM(Gen7RomHandler.java:328)
	at com.dabomstew.pkrandom.romhandlers.Abstract3DSRomHandler.loadRom(Abstract3DSRomHandler.java:69)
	at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$loadROM$106(NewRandomizerGUI.java:778)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.EOFException
	at java.io.RandomAccessFile.readFully(Unknown Source)
	at java.io.RandomAccessFile.readFully(Unknown Source)
	at com.dabomstew.pkrandom.ctr.RomfsFile.getContents(RomfsFile.java:54)
	at com.dabomstew.pkrandom.ctr.NCCH.getFile(NCCH.java:733)
	at com.dabomstew.pkrandom.romhandlers.Abstract3DSRomHandler.readFile(Abstract3DSRomHandler.java:195)
	at com.dabomstew.pkrandom.romhandlers.Gen7RomHandler.computeCRC32sForRom(Gen7RomHandler.java:3648)
	at com.dabomstew.pkrandom.romhandlers.Gen7RomHandler.loadedROM(Gen7RomHandler.java:326)
	... 3 more

--ROM Diagnostics--
**System (please fill in the following information):**
 - Operating System: Windows
 - Randomizer Version: 4.6.0

**If your problem is that you can't randomize a game:**
If you get a popup saying that there has been an "unhandled exception", please attach the error log as an attached file to this issue.

**Comment by darco03** [comment]
Whenever I try to use the randomizer since yesterday it doesnt work anymore I randomised a rom it worked, I died so I started making a new save but then this error kept appearing, I've tried to reinstall the randomizer, new roms nothing is working
Im on windows 11
Randomizer Version: 1720
ROM: Pokemon Platinum (U)
Code: CPUE
Reported Support Level: Complete

com.dabomstew.pkrandom.exceptions.RandomizerIOException: java.io.FileNotFoundException: E:\Pokemon\tmp_PokemonPlatinumVersionUSARev1\poketooltrainertrpokenarc (The process cannot access the file because it is being used by another process)
	at com.dabomstew.pkrandom.romhandlers.Gen4RomHandler.setTrainers(Gen4RomHandler.java:1407)
	at com.dabomstew.pkrandom.romhandlers.AbstractRomHandler.randomizeTrainerPokes(AbstractRomHandler.java:944)
	at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:292)
	at com.dabomstew.pkrandom.gui.RandomizerGUI$3.run(RandomizerGUI.java:1957)
Caused by: java.io.FileNotFoundException: E:\Pokemon\tmp_PokemonPlatinumVersionUSARev1\poketooltrainertrpokenarc (The process cannot access the file because it is being used by another process)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at com.dabomstew.pkrandom.newnds.NDSFile.writeOverride(NDSFile.java:91)
	at com.dabomstew.pkrandom.newnds.NDSRom.writeFile(NDSRom.java:569)
	at com.dabomstew.pkrandom.romhandlers.AbstractDSRomHandler.writeFile(AbstractDSRomHandler.java:174)
	at com.dabomstew.pkrandom.romhandlers.AbstractDSRomHandler.writeFile(AbstractDSRomHandler.java:165)
	at com.dabomstew.pkrandom.romhandlers.AbstractDSRomHandler.writeNARC(AbstractDSRomHandler.java:114)
	at com.dabomstew.pkrandom.romhandlers.Gen4RomHandler.setTrainers(Gen4RomHandler.java:1405)
	... 3 more
