### ISSUE TITLE
Randomizer endlessly loads

### ISSUE THREAD

**Issue by thelerr** [Ajarmar/universal-pokemon-randomizer-zx#735]
The randomizer wont load any roms. The cmd says,

Exception in thread "Thread-1" java.lang.OutOfMemoryError: Java heap space
        at com.dabomstew.pkrandom.ctr.GARCArchive.readFrames(GARCArchive.java:176)
        at com.dabomstew.pkrandom.ctr.GARCArchive.<init>(GARCArchive.java:71)
        at com.dabomstew.pkrandom.romhandlers.Abstract3DSRomHandler.readGARC(Abstract3DSRomHandler.java:184)
        at com.dabomstew.pkrandom.romhandlers.Gen7RomHandler.getAreaData(Gen7RomHandler.java:1452)
        at com.dabomstew.pkrandom.romhandlers.Gen7RomHandler.loadedROM(Gen7RomHandler.java:303)
        at com.dabomstew.pkrandom.romhandlers.Abstract3DSRomHandler.loadRom(Abstract3DSRomHandler.java:69)
        at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$loadROM$106(NewRandomizerGUI.java:775)
        at com.dabomstew.pkrandom.newgui.NewRandomizerGUI$$Lambda$325/0x0000000100351040.run(Unknown Source)
        at java.base/java.lang.Thread.run(Thread.java:834)

What does this mean?

**Comment by tobiaslain** [comment]
DId you find a fix?
