### ISSUE TITLE
Unable to create a Pokemon White Metronome Only seed

### ISSUE THREAD

**Issue by raphix333** [Ajarmar/universal-pokemon-randomizer-zx#8]
I tried creating a metronome only seed and i get unhandled exceptions. Here's the error log.

Randomizer Version: 1721
ROM: Pokemon White (U)
Code: IRAO
Reported Support Level: Complete

java.lang.NullPointerException
	at com.dabomstew.pkrandom.RomFunctions.getMovesAtLevel(RomFunctions.java:111)
	at com.dabomstew.pkrandom.RomFunctions.getMovesAtLevel(RomFunctions.java:99)
	at com.dabomstew.pkrandom.romhandlers.Gen5RomHandler.setTrainers(Gen5RomHandler.java:1206)
	at com.dabomstew.pkrandom.romhandlers.AbstractRomHandler.metronomeOnlyMode(AbstractRomHandler.java:2015)
	at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:370)
	at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$performRandomization$77(NewRandomizerGUI.java:586)
	at java.lang.Thread.run(Unknown Source)

[error_2020-08-07-09-42-59.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5041803/error_2020-08-07-09-42-59.txt)

**Comment by tom-overton** [comment]
Hey raphix333,

Thanks for the report! I did an investigation and discovered this was broken starting in v3.1.0. I fixed it with this commit, which will be included in the upcoming v4.0 release: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/commit/72ea0e6e4819bfe6deaff5f9b50bff96498196cb

Until then, please use v3.0.2 if you want to make a Metronome Only seed. You can grab it here: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases/tag/v3.0.2
